#!/bin/bash
#HACKERROR         ##
#github:2336604775 ##
#web:hackerror.top ##
#####################
export ver="1.1.2"
if [ -f "$PREFIX/var/dpcache" ];then
echo "看不见我" 1>/dev/null 2>&1
  else
  echo "安装工具中…"
  apt install gzip zip xz-utils bzip2 tar -y
  touch $PREFIX/var/dpcache
  clear
fi
export var=`curl -fsSL http://hackerror.top/bowh/dpcache`
if [ x"$1" == x ];then
echo "版本$ver"
echo "最新版本$var"
echo "现支持.tar gz tar.gz bz2 tar.bz2 bz(仅解压) zip"
echo ".tar.xz"
echo "*tar系为打包"
echo "用法:dp 模式 文件/目录 压缩文件名 压缩方式"
echo "模式:"
echo "u      #更新"
echo "d      #解压文件"
echo "c      #压缩文件"
echo "*gz压缩可不用指定压缩文件名"
elif [ $1 == c ];then
echo "您已选择压缩模式"
  if [ x"$2" == x ];then
  echo "请指定目录"
  elif [ $4 == tar ];then
  tar cvf $3 $2
  echo "压缩成功"
  elif [ $4 == gzip ];then
  gzip -k $3
  echo "压缩成功"
  elif [ $4 == tar.gz ];then
  tar zcvf $3 $2
  echo "压缩成功"
  elif [ $4 == bz2 ];then
  bzip2 -z $3
  echo "压缩成功"
  elif [ $4 == tar.bz2 ];then
  tar jcvf $3 $2
  echo "压缩成功"
  elif [ $4 == tar.xz ];then
  tar -Jcf $3 $2
  echo "压缩成功"
  elif [ $4 == zip ];then
  zip $3 $2
  echo "压缩成功"
  else
  echo "暂不支持这种格式或命令输入错误"
  fi
elif [ $1 == d ];then
echo "您已选择解压模式"
file_name=$2
hz=${file_name#*.}
echo "后缀名为:"
echo $hz
if [ x"$2" == x ];then
echo "请指定一个文件"
elif [ $hz == tar ];then
tar xvf $2
elif [ $hz == gz ];then
gzip -d $2
elif [ $hz == tar.gz ];then
tar zxvf $2
elif [ $hz == bz2 ];then
bzip2 -d $2
elif [ $hz == tar.bz2 ];then
tar jxvf $2
elif [ $hz == bz ];then
bzip2 -d $2
elif [ $hz == zip ];then
unzip $2
elif [ $hz == tar.xz ];then
tar -Jxf $2
else
echo "自动检测失败，请在文件名后输入文件后缀以手动解压"
if [ x"$3" == x ];then
echo "正在使用自动检测"
elif [ $3 == tar ];then
echo "正在手动解压"
tar xvf $2
elif [ $3 == gz ];then
echo "正在手动解压"
gzip -d $2
elif [ $3 == tar.gz ];then
echo "正在手动解压"
tar zxvf $2
elif [ $3 == bz2 ];then
echo "正在手动解压"
bzip2 -d $2
elif [ $3 == tar.bz2 ];then
echo "正在手动解压"
tar jxvf $2
elif [ $3 == bz ];then
echo "正在手动解压"
bzip2 -d $2
elif [ $3 == zip ];then
echo "正在手动解压"
unzip $2
elif [ $3 == tar.xz ];then
tar -Jxf $2
echo "正在手动解压"
else
echo "后缀名输入错误或暂不支持这种压缩文件"
fi
fi
elif [ $1 == u ];then
cd ~
apt install curl -y 1>/dev/null 2>&1
curl -o update.sh http://hackerror.top/bowh/update.sh
chmod +x update.sh
./update.sh
else
echo "没有这个模式"
fi

